CREATE TABLE ListaDeseos
(
    [IDDESEOS][INT] IDENTITY (1,1) NOT NULL,
    [IDPRODUCTO][INT] NOT NULL,
    [IDCLIENTE][INT] NOT NULL,
    CONSTRAINT PK_IDDESEOS PRIMARY KEY (IDDESEOS),
    CONSTRAINT FK_IDPRODUCTO_DESEOS FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO),
    CONSTRAINT FK_IDCLIENTE_DESEOS FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
)
GO


IF EXISTS
(
    SELECT type_desc, type
    FROM sys.procedures
    WHERE NAME = 'RecordWishList'
    AND TYPE = 'p'
)
DROP PROCEDURE dbo.RecordWishList
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE RecordWishList
(
    @idproducto INT,
    @idusuario INT
)
AS 
BEGIN
    SET NOCOUNT ON
    DECLARE @MSG VARCHAR(10)
    BEGIN TRAN WL
    BEGIN TRY
        INSERT INTO DBO.ListaDeseos(IDPRODUCTO, IDCLIENTE)
        VALUEs(@idproducto, @idusuario)
        SET @MSG = 'iNGRESADO'
        COMMIT TRAN WL 
    END TRY
    BEGIN CATCH
        SET @MSG = 'NO SE PUDO'
        ROLLBACK TRAN WL 
    END CATCH
    SELECT @MSG
END
GO