//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int IdAdmin { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public int IdPersona { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
