//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.DetalleCompra = new HashSet<DetalleCompra>();
        }
    
        public int IdCompra { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int IdTipoP { get; set; }
        public double IVA { get; set; }
        public double Total { get; set; }
        public int IdCliente { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
